# Generated by Django 4.2.5 on 2024-05-25 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='fotos',
        ),
        migrations.AddField(
            model_name='livro',
            name='foto',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Foto',
        ),
    ]
