# Generated by Django 4.2.5 on 2024-05-26 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_autor_alter_livro_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='nome',
            field=models.CharField(default='Mauricio', max_length=200),
            preserve_default=False,
        ),
    ]
