# Generated by Django 4.2.5 on 2024-05-28 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_autor_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autor',
            name='autorFk',
        ),
        migrations.AddField(
            model_name='itemlivro',
            name='qtd_livro',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
